version: 2.1

# These "CircleCI Orbs" are reusable bits of configuration that can be shared
# across projects.  See https://circleci.com/orbs/ for more information.
orbs:
  # `oss` is a local reference to the package.  The source for Apollo Orbs can
  # be found at http://github.com/apollographql/CircleCI-Orbs.
  oss: apollo/oss-ci-cd-tooling@0.0.5

commands:
  # These are the steps used for each version of Node which we're testing
  # against.  Thanks to YAMLs inability to merge arrays (though it is able
  # to merge objects), every version of Node must use the exact same steps,
  # or these steps would need to be repeated in a version of Node that needs
  # something different.  Probably best to avoid that, out of principle, though.
  common_test_steps:
    description: "Commands to run on every Node.js environment"
    steps:
      - oss/install_specific_npm_version
      - checkout
      - oss/npm_clean_install_with_caching
      - run:
          command: npm run check

# Important! When adding a new job to `jobs`, make sure to define when it
# executes by also adding it to the `workflows` section below!
jobs:
  # Platform tests, each with the same tests but different platform or version.
  # The docker tag represents the Node.js version and the full list is available
  # at https://hub.docker.com/r/circleci/node/.
  NodeJS 12:
    executor: { name: oss/node, tag: '12' }
    steps:
      - common_test_steps

  Publish:
    executor: { name: oss/node, tag: '12' }
    steps:
      - common_test_steps
      - run:
          command: npm run push

common_publish_filters: &common_publish_filters
  filters:
    branches:
      # If 'docs' is found, with word boundaries on either side, skip.
      only: /.*?\bmaster\b.*/

workflows:
  version: 2
  Build:
    jobs:
      - NodeJS 12
      - Publish:
          <<: *common_publish_filters
          requires:
            - NodeJS 12
