[build]
  publish = "docs/public/"
  command = "git status"
  # command = "git status && gatsby build --prefix-paths && mkdir -p apollo-server && mv public/* apollo-server && mv apollo-server public/"
[build.environment]
  NPM_VERSION = "6"
