blank_issues_enabled: false
contact_links:
  - name: Stack Overflow questions tagged "apollo"
    url: https://stackoverflow.com/questions/tagged/apollo
    about: >-
      Many questions are already answered on Stack Overflow!
      We suggest starting here!
  - name: Spectrum Community Support
    url: https://spectrum.chat/apollo/apollo-server
    about: >-
      If you're unable to find an answer on Stack Overflow, the Apollo
      Server channel on our Apollo Community Spectrum is the next best place.
